### ISSUE TITLE
PHP ^7.0

### ISSUE THREAD

**Issue by lukesnowden** [lukesnowden/google-shopping-feed#10]
Anyone know why namespacing is collapsing running PHP7?

**Comment by mackieee** [comment]
@lukesnowden First most, used your library today - works a treat! :) It's awesome! Secondly, In regards to your issue, I ran this under 7.0.14 - had no problems?

**Comment by lukesnowden** [comment]
hmmmm got colleagues reporting issues with 7, ill see if I can isolate the issue, glad its working fine for you.
