### ISSUE TITLE
Problem when running over CLI

### ISSUE THREAD

**Issue by mikeburke-adz** [lukesnowden/google-shopping-feed#11]
When calling Feed->asRss() when running over the CLI (an Artisan command) I get the error "ErrorException: ob_end_clean(): failed to delete buffer. No buffer to delete in ...\vendor\lukesnowden\google-shopping-feed\src\LukeSnowden\GoogleShoppingFeed\Feed.php:262"

The code runs fine when the same command is run through the browser.

**Comment by lukesnowden** [comment]
think that should fix it

**Comment by mikeburke-adz** [comment]
That's great, thanks
