### ISSUE TITLE
Price Node does not include ISO 4217 Country Currency

### ISSUE THREAD

**Issue by mackieee** [lukesnowden/google-shopping-feed#12]
Currently the price node has a float value of:

```
<g:price>15.00</g:price>
```

However in the current specification; it requires a second value adjacent to the numeric value of the originating countries currency. 

Syntax 
- Numeric
- [ISO 4217](http://www.iso.org/iso/home/standards/currency_codes.htm)

For E.g.

```
<g:price>15.00 USD</g:price>
```
The specification hasn't got a timestamp of when this was included.

[Google Price Specification link](https://support.google.com/merchants/answer/6324371)

Add a constant list of all the supported possible Currencies? Default to `USD` if not present?

**Comment by lukesnowden** [comment]
Just had a little read. Correct me if I'm wrong but this is placed in the "best practices" section. The minimum requirement is to have the corresponding amount on the landing page with the correct currency symbol assigned.  


>Minimum requirements
These are the requirements you'll need to meet to show ads for your product. If you don't follow these requirements, we'll disapprove your product and let you know in the Diagnostics page of your Merchant Center account. 

>Make sure that the price on your product data meets the landing page requirements. Learn more about requirements for Google Shopping landing pages.
Submit an amount and currency that matches the price on your landing page. Learn more currency requirements for your target country.
Include the price in the currency of your target country prominently on your landing page.

**Comment by mackieee** [comment]
Afternoon! I don't believe so, those minimum requirements & best practices seem to be their checklist for best endeavour of your feed being accepted.

The format table specifically implies that there's a requirement for it. 

### Format
Follow these formatting guidelines to make sure that we understand the data you're submitting. 

**Type**:	Number plus currency (use ISO 4217)

| File format | Example value |
|---|---|
| Text feeds   | 15.00 GBP  |
|  XML feeds  | `<g:price>15.00 GBP</g:price>`  |

Having said that, I've utilised this awesome library this week :) Of which, I had encountered feed validation errors when I was uploading my products in Google Merchant Centre. Whereas I had to include the Currency Symbol.

**Comment by lukesnowden** [comment]
Hmmm. We have around 200 ecommerce sites using this and there has not been any issues raised. Ill pass it over to our marketing/retainer department and see if there has been any reported issues. It is something that needs to be addressed either way.

**Comment by mackieee** [comment]
I thought I'd do re-test just quickly with a test feed without the Currency; which validated fine. So I must of seen something different :/ Apologies. Indeed, I'm sure you would of heard something about long ago with that many! :) 

Thanks lukesnowden anyways!

**Comment by m2de** [comment]
I'm aware this is quite an old thread but just came across this issue and thought I would help clarify this for anyone else who runs into this. Google will report the currency as missing from the price field unless a default currency is set for the feed in the merchant center.

**Comment by marie-de-ubeda** [comment]
Hello, 
I think I have the same issue: 
if the price is rounded <g:price>39.00</g:price>. Google Merchant center will report no error. But if the price is  <g:price>8.90</g:price> Google Merchant center report I have to specify a ISO 4217 Country Currency. In my case, I need to send <g:price>8.90 EUR</g:price> in my feed. 
How I can do that ? $item->price($price." EUR"); send me an error (A non well formed numeric value encountered) 
Thank you for work and you your help.

**Comment by lukesnowden** [comment]
I have just quickly knocked up a method;

```php
use LukeSnowden\GoogleShoppingFeed\Containers\GoogleShopping;

GoogleShopping::title('Test Feed');
GoogleShopping::link('http://example.com/');
GoogleShopping::description('Our Google Shopping Feed');
GoogleShopping::setIso4217CountryCode('EUR');
```

This should work, let me know if it doesnt because I have not tested it

**Comment by lukesnowden** [comment]
Also note that I've updated the version to `^2.1` 👍

**Comment by 2linkto** [comment]
Thank you very much for you quick answer. I have updated to ^2.1, tested , fetched in Google Merchant Center and all is ok now. No more errors. You save my day :)

**Comment by lukesnowden** [comment]
No worries 👍

**Comment by marie-de-ubeda** [comment]
Thank you very much for your quick answer. I have updated to ^2.1, tested and fetched in Google Merchant Center and it works now. No More error. You save my day :)
