### ISSUE TITLE
Namespace issue

### ISSUE THREAD

**Issue by mikeburke-adz** [lukesnowden/google-shopping-feed#14]
I'm having different behaviour using your package on my production environment using php 7.0.15 than on my development environment using php 7.0.8.

In my production environment the namespace tags do not seem to be formed correctly - "<g:id/><id>1</id>" and "<g:price/><price>12.50</price>".

In my development environment they are created correctly - "<g:id>1</g:id>" and "<g:price>12.50</g:price>".

I noted in issue 10 [https://github.com/lukesnowden/google-shopping-feed/issues/10](https://github.com/lukesnowden/google-shopping-feed/issues/10) you have had namespace issues reported in php ^ 7.0. Does this issue match those previously reported? If so did you manage to isolate the cause?

Thanks in advance.

**Comment by lukesnowden** [comment]
Hi, this was recently fixed https://github.com/lukesnowden/google-shopping-feed/commit/c73c45a1a5effb8e3fdedff369aa0b92cc719aa3 it was down to XML versions installed on the server. Can you verify you are using the latest version?

**Comment by lukesnowden** [comment]
And yes that was the same issue :-)

**Comment by mikeburke-adz** [comment]
Ah, I was using an old version yes, unfortunately this change seems to expose another issue. After updating, I'm now getting "ErrorException: SimpleXMLElement::addChild(): unterminated entity reference  Dry Latex - 80 Grit]]&gt; in .../vendor/lukesnowden/google-shopping-feed/src/LukeSnowden/GoogleShoppingFeed/Node.php:89".

A little research highlights similar issues in other packages: 
[https://github.com/cornernote/php-google-spreadsheet-client/commit/30416d02289cdeec314d3b8fb374d6c87f4f57f8](https://github.com/cornernote/php-google-spreadsheet-client/commit/30416d02289cdeec314d3b8fb374d6c87f4f57f8) 
[https://github.com/asimlqt/php-google-spreadsheet-client/issues/157](https://github.com/asimlqt/php-google-spreadsheet-client/issues/157)
[http://stackoverflow.com/questions/17027043/unterminated-entity-reference-php/29679217#29679217](http://stackoverflow.com/questions/17027043/unterminated-entity-reference-php/29679217#29679217)

I made a change to wrap $this->value in htmlspecialchars() on line 89 of Node.php, it resolved the error and the output looks good.

**Comment by mikeburke-adz** [comment]
I submitted a pull request for the change [https://github.com/lukesnowden/google-shopping-feed/pull/15](https://github.com/lukesnowden/google-shopping-feed/pull/15)

**Comment by lukesnowden** [comment]
looks sound to me 👍
