### ISSUE TITLE
Item description is not correct

### ISSUE THREAD

**Issue by Vansamang** [lukesnowden/google-shopping-feed#2]
If i check the example feed for google shopping. the description should be a new tag like so
`<description>` (https://support.google.com/merchants/answer/160589?hl=en
In your code it is generated as
`<g:description>` .
Can this be changed?

**Comment by lukesnowden** [comment]
Any idea on when this came into play?

**Comment by lukesnowden** [comment]
Just downloaded the example file located https://support.google.com/merchants/answer/160589?hl=en and the `<g:description>` is correct
