### ISSUE TITLE
Add custom attributes

### ISSUE THREAD

**Issue by annuh** [lukesnowden/google-shopping-feed#23]
It would be nice if we could add custom attributes, for example to include some specific product details.

This data cannot be used by Google directly, but it could be used by other services that support Shopping Feeds.

Do you like this feature?
I could create a PR for this if you'd like.

**Comment by lukesnowden** [comment]
In two minds with this one. One side of the coin, this is a "Google shopping feed generator" it's for that very purpose. On the other side if it can be used for other feeds that quite cool.

Will Google not throw a hissy fit sending across nodes that it does not require?

**Comment by annuh** [comment]
No, I don't think Google mind if the Shopping feed contains extra fields. As long as all required fields are present.

It will be sufficient if there is an extra method `custom($attributeName, $attributeValue)`, right?

**Comment by lukesnowden** [comment]
As long as there's no issues feel free to make a PR!
