### ISSUE TITLE
I want to create multiple feeds in one batch

### ISSUE THREAD

**Issue by johanlerche** [lukesnowden/google-shopping-feed#32]
The problem I face is that I need a new instance of the Feed class in order to create multiple feeds in one batch, the Item class is accessing the Feed object through the static singleton implementation, which in my eyes is a design flaw since I only ever can generate one feed in the same batch. Hence I need to be able to instantiate the feed outside a static context to allow for multiple feeds in the same batch.

Please accept my PR https://github.com/lukesnowden/google-shopping-feed/pull/30 it should not break anything and still let you use the static wrapper in the same way :-)

**Comment by lukesnowden** [comment]
new release at `2.2.0` with your pull requests in place.
