### ISSUE TITLE
SimpleXMLElement::asXML(): xmlEscapeEntities : char out of range

### ISSUE THREAD

**Issue by east2dd** [lukesnowden/google-shopping-feed#46]
<img width="1213" alt="Screenshot 2021-01-27 at 00 37 43" src="https://user-images.githubusercontent.com/790329/105859153-ed8f6e80-6037-11eb-8135-6dc6444636df.png">

**Comment by lukesnowden** [comment]
Please convert your data to UTF-8.

**Comment by east2dd** [comment]
hmmm, I guess it would be easier to convert data line #292. Or It would be great if `asRss` method take `encoding` param.

**Comment by east2dd** [comment]
I made it work adding `<?xml version="1.0" encoding="utf-8" standalone="yes"?>` before `rss` tag in constructor.
@lukesnowden 
```
public function __construct()
    {
        $this->feed = new SimpleXMLElement('<?xml version="1.0" encoding="utf-8" standalone="yes"?><rss xmlns:g="' . $this->namespace . '" version="' . $this->version . '"></rss>');
    }
```

**Comment by east2dd** [comment]
Can I contribute to this repo? Can I open a PR? @lukesnowden

**Comment by lukesnowden** [comment]
Please do.

**Comment by xyingsoft** [comment]
Would you give me access to this repo? @lukesnowden

**Comment by lukesnowden** [comment]
Fork and Clone then create a PR

**Comment by east2dd** [comment]
Ok

**Comment by east2dd** [comment]
Please review @lukesnowden https://github.com/lukesnowden/google-shopping-feed/pull/47

**Comment by lukesnowden** [comment]
Tagged as 2.2.7

**Comment by east2dd** [comment]
```
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - Root composer.json requires lukesnowden/google-shopping-feed ^2.2.7, it is satisfiable by lukesnowden/google-shopping-feed[2.2.7] from composer repo (https://repo.packagist.org) but lukesnowden/google-shopping-feed[dev-master, 1.0.0, ..., 1.2.0, 2.0.0, 2.0.1] from vcs repo (github https://github.com/dmaksimov/google-shopping-feed.git) has higher repository priority. The packages with higher priority do not match your constraint and are therefore not installable. See https://getcomposer.org/repoprio for details and assistance.
```

I got this error while bump version to 2.2.7 🤔

**Comment by lukesnowden** [comment]
Clear your local cache `$ composer clearcache`
