### ISSUE TITLE
Problem when creating a variant

### ISSUE THREAD

**Issue by s-duval** [lukesnowden/google-shopping-feed#7]
Fatal error: Call to a member function get() on a non-object in LukeSnowden/GoogleShoppingFeed/Item.php on line 399

**Comment by lukesnowden** [comment]
@endelwar would any of your changes be the reason for this? - cheers

**Comment by s-duval** [comment]
it happens when mpn is not set before creating a variant

**Comment by lukesnowden** [comment]
Yeah I can see that now, sorry not worked on this for a while! Suggestions? Throw an Exception if mpn isn't set on the initial item or create a random identifier for the group? Makes sense to force an mpn, can't remember if Google throws a wobbly if its not there or not.

**Comment by endelwar** [comment]
based on google documentation gtin and mpn are required (https://support.google.com/merchants/answer/7052112), but if both of them are missing an identifier_exists must be set to false (https://support.google.com/merchants/answer/6324478)

**Comment by lukesnowden** [comment]
I believe an exception to be suitable then as you could have mpn or gtin but you may have not set it yet. 

Not overly keen on using a random identifier as its harder to find the item in the xml file. Thoughts?

**Comment by endelwar** [comment]
Yes, I agree with you, correctness of data should be checked before generating the feed, so an Exception (maybe a custom one like MissingIdentifierException) should be thrown
